version: '3'

services:
  terraform:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/work
      - ./.aws:/root/.aws
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - ENV=${ENV}
    working_dir: /work
    entrypoint: /bin/bash 